//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVMNextGenWebAutomation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataQA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataQA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVMNextGenWebAutomation.TestDataQA", typeof(TestDataQA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@fleettracker.
        /// </summary>
        internal static string AdminDev {
            get {
                return ResourceManager.GetString("AdminDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avmliteqa.
        /// </summary>
        internal static string AdminDevPassword {
            get {
                return ResourceManager.GetString("AdminDevPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@fleetmanager.
        /// </summary>
        internal static string AdminFM {
            get {
                return ResourceManager.GetString("AdminFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fleetmanager007.
        /// </summary>
        internal static string AdminFMPassword {
            get {
                return ResourceManager.GetString("AdminFMPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avmliteqa.
        /// </summary>
        internal static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@fleettracker.
        /// </summary>
        internal static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://avmnextgenserviceqa.azurewebsites.net/.
        /// </summary>
        internal static string APIBaseAddress {
            get {
                return ResourceManager.GetString("APIBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://avmnextgenloginqa.azurewebsites.net/.
        /// </summary>
        internal static string APIBaseAddressLogin {
            get {
                return ResourceManager.GetString("APIBaseAddressLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fleettrackerkubqa.netstaraus.com.au/.
        /// </summary>
        internal static string APIBaseAddressReport {
            get {
                return ResourceManager.GetString("APIBaseAddressReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fleettrackerqa.netstaraus.com.au/login.
        /// </summary>
        internal static string BaseAddress {
            get {
                return ResourceManager.GetString("BaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter1234.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G%*E@puF52GmQ^^ELZQnM%ZxPYh$N&amp;8p!CJrSeS#4XE%kE5XtZ!^c9+8U5gQaQAk.
        /// </summary>
        internal static string ReCaptchaToken {
            get {
                return ResourceManager.GetString("ReCaptchaToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
